<?php return array (
  'web' => 
  array (
    'domain' => 'www.51ycbb.com,www.rzyjq.com,www.yunzhaizhijian.com,www.linghuaqiandai.cn,www.linghuaqiandai.com,www.linghuaqingdai.com,www.haoxi360.cn,www.linghuaqiandai.cn,www.linghuaqiandai.com,www.linghuaqingdai.com,www.haoxi360.cn,www.shiji8.com,www.haoxi360.com,www.haoxi360.cn,www.dai898.com,www.dai898.cn,www.linghuaqiandai.cn,www.linghuaqianda',
    'name' => '好好数据',
    'title' => '好好数据,您的金融数据专家!集数据表单,审批,微信的云平台.',
    'keywords' => '金融审批系统,数据表单,表单提交,微信数据平台',
    'description' => '好好数据',
    'top_welcome_info' => '好好数据欢迎您！',
    'language' => 'chinese_simplified',
    'auto_debug' => true,
    'phone_show_cloud_bottom' => true,
    'request_geolocation' => true,
    'auth_login_direct_create' => false,
    'weixin_auto_login' => false,
    'search_url' => './index.php?cloud=mall.goods_list&search=',
    'search_placeholder' => '搜索其实很简单',
    'diy_meta' => '<meta property=&#34;qc:admins&#34; content=&#34;1614134767657601667167&#34; />',
    'wid' => '',
    'wx_withdraw_auto_pay' => true,
    'authcode_push_mode' => 'sms',
    'other_push_mode' => 'email',
    'circle' => false,
    'login_position' => true,
    'map_api' => 'baidumap',
    'map_secret' => '3DFc4LtsLRuAs9Ml2EWu1espDB1NIHGj',
    'gps_x' => '0.011',
    'gps_y' => '0.003',
    'img_max' => '5068',
    'site_id' => '1',
    'site_key' => 'd3d7ddd2e742ab4df620aa304f5bc970',
    'cloud_username' => 'haohaoshuju',
    'cloud_password' => 'd3d7ddd2e742ab4df620aa304f5bc970',
  ),
  'api' => 
  array (
    'sms_money' => '0.5',
  ),
  'openid_notice_template' => 
  array (
    'OPENTM203026900' => 'HFsj2TYbEFxYvX8S4bYpfttdKkoGNbi1FqaTcL5q5OU',
    'OPENTM201673425' => 'h4CagyEofaIszUtohM_VORuIrQ-gJuNoltoh4Zsc_-I',
    'TM00003' => 'NGqt635unFB8esRoCNYcAyQQAdcPhb1h3CibzJD0vG8',
    'TM00335' => 'y1aT7ImNUt5a23PRqtKDwIzvDVSs1OfwqUyaMHl5wEQ',
    'OPENTM205258520' => '-JhAF6VXQ2f-OrNZZUVYhzkzoSefkTt47ujNCn0WI1c',
    'TM00891' => 'Zy4RBgn2tLCsvDIT7blGm2B-P0cYVEUDswDjcYux4eI',
    'OPENTM207112032' => '7upqdth5FSwc_CdMPcvuOWU0ihie74I3jn6HvU9-Vn0',
    'OPENTM204690186' => 'Vz2kpLJQAIpmfvHIao9A6tyDhOiMln0nTL_DI_N9udg',
    'OPENTM200565259' => '3P_znkltdF2GpawPuk3TdRNljSe_Vv9duXPGltlBnEo',
    'OPENTM200750297' => '1tSpIzInfEhb-1zN2hKUlKUdXRJ1ZkG173vAZnnzUcY',
    'OPENTM201490123' => '-l6mkrG8LQMSB6rbM3e04SI6UX9mxj9nlXrtkoVgWCM',
    'OPENTM204146731' => 'hBLHrm8x8gG9t4NNQNheTuJfieDZgqpq8d_MvjoWRIQ',
    'OPENTM202849987' => 'F51Qzi5XzQAk2S_WyViaXmujVfLT6DJDfDlkT9EeIyE',
  ),
  'reg_set' => 
  array (
    'phone' => false,
    'email' => false,
    'check' => 'image',
    'user_agreement_url' => './index.php?cloud=diypage.show&id=123',
    'default_group_id' => '13',
    'en_group_id' => '92',
  ),
  'credits_set' => 
  array (
    'rate' => '0',
    'login' => '0',
    'share' => '0',
    'introduce' => '0',
  ),
  'cache' => 
  array (
    'sql_cache_switch' => true,
    'cache_switch' => false,
    'cache_time' => 60,
    'cache_type' => 'memcache',
    'memcache_host' => 'localhost',
    'memcache_port' => 11211,
  ),
  'upload' => 
  array (
    'upAllowSuffix' => 'jpg,png,gif,zip,rar,apk,htm,gzip,ttf,ico,html,ptxt,3gp,rm,rmvb,wmv,avi,mpg,mpeg,mp4,mp3,wma,wav,amr,txt,jpeg,csv,bmp,tiff,pcx,tga,exif,fpx,svg,psd,cdr,pcd,dxf,ufo,eps,ai,raw,WMF,jp2,wbmp,mbm',
    'upImgSuffix' => 'jpg,png,gif,ico,jpeg,csv,bmp,tiff,pcx,tga,exif,fpx,svg,psd,cdr,pcd,dxf,ufo,eps,ai,raw,WMF,jp2,wbmp,mbm',
    'sys_upload_max_filesize' => 1000000,
    'sys_post_max_size' => 1000000,
    'upload_path' => './upload/',
  ),
  'server' => 
  array (
    'os_charset' => 'gbk',
  ),
  'sms' => 
  array (
    'sms_country' => '+86',
    'sms_api' => 'haoserver',
    'sms_key' => 'bbf3b0feae8640cb861cd296291e6a77',
    'success_val' => '∈0}',
    'fail_email' => '1084212434@qq.com',
    'frequency_limit' => '1:1/3:2/5:3/10:6/30:10/60:15/1440:20/10080:30/43200:60',
    'examined_template_id' => '2088',
    'examined_template_content' => ',请耐心等待.',
    'recheck_template_id' => '2116',
    'recheck_template_content' => ',请加我们的审核员微信号:{weixin}.请关注我们公众号：信誉牛牛超市',
    'succeed_template_id' => '2088',
    'succeed_template_content' => ',恭喜您,请加您的服务专员微信号{weixin}.',
    'fail_template_id' => '2088',
    'fail_template_content' => ',请您保持良好信用,以便以后再次申请.',
    'other_template_id' => '39349',
  ),
  'unlogin_function_power' => 
  array (
    0 => 'index.head',
    1 => 'index.top_bar',
    2 => 'index.user_position',
    3 => 'index.visitor_position',
    4 => 'index.login',
    5 => 'index.resetPassword',
    6 => 'index.reg_user',
    7 => 'index.diy_phone_home_page',
    8 => 'index.navigation',
    9 => 'index.foot',
    10 => 'diypage.show',
    12 => 'index.closed',
    13 => 'server.program_market',
    14 => 'server.program_detail',
    15 => 'server.program_screenshot',
    16 => 'server.program_server',
    17 => 'server.template_market',
    18 => 'server.template_detail',
    19 => 'server.template_screenshot',
    20 => 'server.template_server',
    21 => 'index.device',
    22 => 'index.robot',
    23 => 'index.not_found',
    24 => 'index.customer_service',
    25 => 'slider.show',
    26 => 'diypage.show_content',
    27 => 'diypage.show_list',
    28 => 'image.show',
    29 => 'image.show_content',
    30 => 'image.show_list',
    31 => 'image.show_thumb',
    32 => 'image.show_type',
    33 => 'diypage.show_type',
    34 => 'diypage.show_page_list',
    35 => 'article.show',
    36 => 'article.show_list',
    37 => 'article.show_type',
    38 => 'article.show_article_list',
    39 => 'feedback.add',
    40 => 'feedback.list',
    41 => 'form.data_add',
    42 => 'form.data_show_list',
    43 => 'form.data_show_detail',
    44 => 'diymodule.show',
    45 => 'server.send_sms',
    46 => 'server.inquiry_sms',
    49 => 'index.debug',
    53 => 'talk.type',
    54 => 'talk.title',
    55 => 'talk.content',
    56 => 'talk.type_module',
    57 => 'talk.title_module',
    61 => 'travel.line_detail',
    65 => 'copy.task',
    90 => 'diypage.foot_six_grid',
    91 => 'shop.type_module_two',
    92 => 'menu.module',
    108 => 'image.type_list',
    109 => 'image.type_module',
    142 => 'mall.shop_search',
    144 => 'mall.auto_receipt_expire_order',
    145 => 'weixin.index',
    159 => 'index.oauth_bind_option',
    160 => 'index.phone_bottom',
    161 => 'image.product',
    164 => 'pk.show',
    165 => 'index.circle',
    166 => 'index.circle_module',
    171 => 'axis.show',
  ),
  'image_mark' => 
  array (
    'type' => 'logo',
    'position' => 6,
    'opacity' => 50,
    'water_logo' => 'images/image_mark.png',
    'color' => '102,255,0',
    'font_size' => 38,
    'font_angle' => -45,
    'ttf_path' => '',
  ),
  'other' => 
  array (
    'reg_phone' => '/^1[0-9]{10}$/',
    'user_login_log' => 100,
    'date_style' => 'Y-m-d',
    'timeoffset' => '8',
    'optional_year_range' => '1930-2030',
    'export_csv_charset' => 'gbk',
  ),
  'program' => 
  array (
    'language' => 'chinese_simplified',
    'cache_time' => 8,
    'template' => 'default',
    'imageMark' => true,
    'state' => 'opening',
  ),
  'class_name' => 'index',
  'no_update' => 
  array (
    'cloud_version' => '4.0',
  ),
)?>